# Generated by Django 4.0.2 on 2022-02-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_alter_studentdetail_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
