# Generated by Django 4.0.2 on 2022-02-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
