# Generated by Django 4.0.2 on 2022-02-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0003_alter_studentdetail_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='student_parent_contact',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='student_subjects',
            field=models.ManyToManyField(to='transcripts.Subjects'),
        ),
    ]
