# Generated by Django 4.0.2 on 2022-02-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0005_studentdetail_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='student_picture',
            field=models.ImageField(blank=True, default='default-profilepic.jpg', null=True, upload_to=''),
        ),
    ]
